# Generated by Django 4.2.3 on 2023-07-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_shippingaddress_cash_on_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
